### ISSUE TITLE
500 error when deleting 404 hack attempts

### ISSUE THREAD

**Issue by mattkemp** [kipusoep/UrlTracker#114]
Using Umbraco 7.4 and UrlTracker 3.10

My site has just been penetration tested and as a result I have lots of 404's that I'd like to clear. Trying to delete them throws an error though. It looks like it's passing the hack attempt value (could it use an ID instead?).

I'll look into turning off Request Validation for just this section as a workaround for now.

Here's an example error from the log:

	ERROR Umbraco.Core.UmbracoApplicationBase - An unhandled exception occurred
	System.Web.HttpRequestValidationException (0x80004005): A potentially dangerous Request.Form value was detected from the client (gvNotFound$ctl13$hfOldUrl="test<a aa aaa aaaa aaaaa...").
	   at System.Web.HttpRequest.ValidateString(String value, String collectionKey, RequestValidationSource requestCollection)
	   at System.Web.HttpRequest.ValidateHttpValueCollection(HttpValueCollection collection, RequestValidationSource requestCollection)
	   at System.Web.HttpRequest.get_HasForm()
	   at System.Web.UI.Page.GetCollectionBasedOnMethod(Boolean dontReturnNull)
	   at System.Web.UI.Page.DeterminePostBackMode()
	   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
	   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
	   at System.Web.UI.Page.ProcessRequest()
	   at System.Web.UI.Page.ProcessRequest(HttpContext context)
	   at ASP.umbraco_urltracker_infocaster_umbraco_urltracker_ui_urltrackermanager_aspx.ProcessRequest(HttpContext context) in c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\3cf0696f\a08cb5b4\App_Web_infocaster.umbraco.urltracker.ui.urltrackermanager.aspx.6b1c27ca.ddm0tjpn.0.cs:line 0
	   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
	   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by mattkemp** [comment]
Turned off request validation for UrlTracker by adding this to the web.config, is working now:
	<location path="umbraco/urltracker">
		<system.web>
			<pages validateRequest="false" />
			<httpRuntime requestValidationMode="2.0" />
		</system.web>
	</location>

**Comment by kipusoep** [comment]
This is the way ASP.NET works.
