### ISSUE TITLE
Recognizes the URL but unable to redirect

### ISSUE THREAD

**Issue by mpctilsted** [kipusoep/UrlTracker#121]
Hey there,

I just installed your package on my Umbraco 7.3.8 website and have an issue where i create a redirect rule but i still get the normal Umbraco 404 page.

This is the log:

 2016-03-16 13:38:30,542 [P2648/D48/T29] DEBUG Umbraco.Web.UmbracoModule - Response status: Redirect=none, Is404=true, StatusCode=0
 2016-03-16 13:38:30,542 [P2648/D48/T29] DEBUG InfoCaster.Umbraco.UrlTracker.Helpers.LoggingHelper - UrlTracker HttpModule | AcquireRequestState start
 2016-03-16 13:38:30,542 [P2648/D48/T29] DEBUG InfoCaster.Umbraco.UrlTracker.Helpers.LoggingHelper - UrlTracker HttpModule | AcquireRequestState start
 2016-03-16 13:38:30,542 [P2648/D48/T29] DEBUG InfoCaster.Umbraco.UrlTracker.Helpers.LoggingHelper - UrlTracker HttpModule | Incoming URL is: test2/
 2016-03-16 13:38:30,542 [P2648/D48/T29] DEBUG InfoCaster.Umbraco.UrlTracker.Helpers.LoggingHelper - UrlTracker HttpModule | Incoming URL is: test2/
 2016-03-16 13:38:30,542 [P2648/D48/T29] DEBUG InfoCaster.Umbraco.UrlTracker.Helpers.LoggingHelper - UrlTracker HttpModule | Response statusCode is 404, continue URL matching
 2016-03-16 13:38:30,542 [P2648/D48/T29] DEBUG InfoCaster.Umbraco.UrlTracker.Helpers.LoggingHelper - UrlTracker HttpModule | Response statusCode is 404, continue URL matching
 2016-03-16 13:38:30,543 [P2648/D48/T29] DEBUG InfoCaster.Umbraco.UrlTracker.Helpers.LoggingHelper - UrlTracker HttpModule | Current request's rootNodeId: 1054
 2016-03-16 13:38:30,543 [P2648/D48/T29] DEBUG InfoCaster.Umbraco.UrlTracker.Helpers.LoggingHelper - UrlTracker HttpModule | Current request's rootNodeId: 1054
 2016-03-16 13:38:30,544 [P2648/D48/T29] DEBUG Umbraco.Web.UmbracoModule - Total milliseconds for umbraco request to process: 21.0516
 2016-03-16 13:38:30,544 [P2648/D48/T29] DEBUG InfoCaster.Umbraco.UrlTracker.Helpers.LoggingHelper - UrlTracker HttpModule | EndRequest start
 2016-03-16 13:38:30,544 [P2648/D48/T29] DEBUG InfoCaster.Umbraco.UrlTracker.Helpers.LoggingHelper - UrlTracker HttpModule | EndRequest start
 2016-03-16 13:38:30,544 [P2648/D48/T29] DEBUG InfoCaster.Umbraco.UrlTracker.Helpers.LoggingHelper - UrlTracker HttpModule | Incoming URL is: test2/
 2016-03-16 13:38:30,544 [P2648/D48/T29] DEBUG InfoCaster.Umbraco.UrlTracker.Helpers.LoggingHelper - UrlTracker HttpModule | Incoming URL is: test2/
 2016-03-16 13:38:30,544 [P2648/D48/T29] DEBUG InfoCaster.Umbraco.UrlTracker.Helpers.LoggingHelper - UrlTracker HttpModule | Response statusCode is 404, continue URL matching
 2016-03-16 13:38:30,544 [P2648/D48/T29] DEBUG InfoCaster.Umbraco.UrlTracker.Helpers.LoggingHelper - UrlTracker HttpModule | Response statusCode is 404, continue URL matching
 2016-03-16 13:38:30,544 [P2648/D48/T29] DEBUG InfoCaster.Umbraco.UrlTracker.Helpers.LoggingHelper - UrlTracker HttpModule | Current request's rootNodeId: 1054
 2016-03-16 13:38:30,545 [P2648/D48/T29] DEBUG InfoCaster.Umbraco.UrlTracker.Helpers.LoggingHelper - UrlTracker HttpModule | Current request's rootNodeId: 1054
 2016-03-16 13:38:30,547 [P2648/D48/T29] DEBUG InfoCaster.Umbraco.UrlTracker.Helpers.LoggingHelper - UrlTracker HttpModule | URL match found
 2016-03-16 13:38:30,547 [P2648/D48/T29] DEBUG InfoCaster.Umbraco.UrlTracker.Helpers.LoggingHelper - UrlTracker HttpModule | URL match found
 2016-03-16 13:38:30,547 [P2648/D48/T29] DEBUG InfoCaster.Umbraco.UrlTracker.Helpers.LoggingHelper - UrlTracker HttpModule | Redirect node id: 9911
 2016-03-16 13:38:30,547 [P2648/D48/T29] DEBUG InfoCaster.Umbraco.UrlTracker.Helpers.LoggingHelper - UrlTracker HttpModule | Redirect node id: 9911
 2016-03-16 13:38:30,547 [P2648/D48/T29] DEBUG InfoCaster.Umbraco.UrlTracker.Helpers.LoggingHelper - UrlTracker HttpModule | Redirect url set to: /maerkesager/
 2016-03-16 13:38:30,547 [P2648/D48/T29] DEBUG InfoCaster.Umbraco.UrlTracker.Helpers.LoggingHelper - UrlTracker HttpModule | Redirect url set to: /maerkesager/
 2016-03-16 13:38:30,547 [P2648/D48/T29] DEBUG InfoCaster.Umbraco.UrlTracker.Helpers.LoggingHelper - UrlTracker HttpModule | PassThroughQueryString is enabled
 2016-03-16 13:38:30,548 [P2648/D48/T29] DEBUG InfoCaster.Umbraco.UrlTracker.Helpers.LoggingHelper - UrlTracker HttpModule | PassThroughQueryString is enabled
 2016-03-16 13:38:30,548 [P2648/D48/T29] DEBUG InfoCaster.Umbraco.UrlTracker.Helpers.LoggingHelper - UrlTracker HttpModule | Redirect http code set to: 301
 2016-03-16 13:38:30,548 [P2648/D48/T29] DEBUG InfoCaster.Umbraco.UrlTracker.Helpers.LoggingHelper - UrlTracker HttpModule | Redirect http code set to: 301
 2016-03-16 13:38:30,548 [P2648/D48/T29] DEBUG InfoCaster.Umbraco.UrlTracker.Helpers.LoggingHelper - UrlTracker HttpModule | Response redirectlocation set to: /maerkesager/
 2016-03-16 13:38:30,548 [P2648/D48/T29] DEBUG InfoCaster.Umbraco.UrlTracker.Helpers.LoggingHelper - UrlTracker HttpModule | Response redirectlocation set to: /maerkesager/

If i check the "force redirect", the redirect works like its supposed to.
I am using Umbraco as a Service but that shouldnt be of any issue, since its on my local machine.

Help please :-(

**Comment by mpctilsted** [comment]
I should say that renaming a node also works just fine.
The only problem is when i create a new rule and do not check force redirect.

**Comment by mpctilsted** [comment]
The installed version is 3.11

**Comment by mpctilsted** [comment]
I found this error in my Elmah log:

System.Web.HttpException (0x80004005): Server cannot set status after HTTP headers have been sent.
   at System.Web.HttpResponse.set_StatusCode(Int32 value)
   at InfoCaster.Umbraco.UrlTracker.Modules.UrlTrackerModule.UrlTrackerDo(String callingEventName, Boolean ignoreHttpStatusCode) in D:\kipusoep\Documents\GitHub\UrlTracker\Modules\UrlTrackerModule.cs:line 349
   at InfoCaster.Umbraco.UrlTracker.Modules.UrlTrackerModule.context_EndRequest(Object sender, EventArgs e) in D:\kipusoep\Documents\GitHub\UrlTracker\Modules\UrlTrackerModule.cs:line 60
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by mpctilsted** [comment]
Not to be an idiot or anything, i really appreciate what you have done here. But im kinda in a rush to get this working, so is it possible to get any support on this soon or would you suggest i fetch the source code and try to fix this on my own?

Regards,

**Comment by kipusoep** [comment]
I'm on holiday...

**Comment by daniel-chenery** [comment]
I'm closing this due to age, and a lot of changes have gone into the lines of code you've mention.
UAAS has also become Umbraco Cloud with its own improvements.

If you still get the issue though, feel free to re-open
