### ISSUE TITLE
Installation error on umbraco 7.4.3

### ISSUE THREAD

**Issue by f000** [kipusoep/UrlTracker#141]
Hi!

I'm unable to install UrlTracker 3.11 on umbraco 7.4.3:

```
2016-08-09 10:59:39,487 [P9096/D8/T7] ERROR Umbraco.Core.UmbracoApplicationBase - An unhandled exception occurred
System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> System.Web.HttpException (0x80004005): The file '/Umbraco/UrlTracker/InfoCaster.Umbraco.UrlTracker.UI.Installer.UrlTrackerInstaller.ascx' does not exist.
   at System.Web.UI.Util.CheckVirtualFileExists(VirtualPath virtualPath)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.UI.TemplateControl.LoadControl(VirtualPath virtualPath)
   at umbraco.presentation.developer.packages.Installer.ProcessInstall(String currentStep)
   at umbraco.presentation.developer.packages.Installer.Page_Load(Object sender, EventArgs e)
   at System.Web.UI.Control.OnLoad(EventArgs e)
   at umbraco.BasePages.BasePage.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at ASP.umbraco_developer_packages_installer_aspx.ProcessRequest(HttpContext context) in c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\154e14b2\841b7026\App_Web_installer.aspx.5d1c7564.asl0a_bi.0.cs:line 0
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

installed modules:

MediaProtect 1.6.2
Lecoati.LeBlender 1.0.8.4
Lucene.Net.Contrib 2.9.4.1
MailChimp.NET 1.1.8
uSync 3.1.4.740

**Comment by lukefrake** [comment]
:+1: I'm experiencing this as well

**Comment by granthughes** [comment]
Using a brand new Umbraco 7.4.3 instance, I have not been able to reproduce this. I tried installing the package via nuget, via the Umbraco Package Repository in the developer section of the admin, and I tried installing from a local package using the zip downloaded from [here](https://our.umbraco.org/projects/developer-tools/301-url-tracker/).

How are either of you trying to do the install? Have you tried one of the methods I mentioned?
