### ISSUE TITLE
Installation failed on Umbraco Cloud

### ISSUE THREAD

**Issue by cgarveyie** [kipusoep/UrlTracker#155]
Errors as listed below

`Installing the dashboard failed: Unable to add dashboard: StartupDashboardSection not found in ~/config/dashboard.config`

```
Well, this is awkward... It seems an error has occurred :-(
Please post a topic at the forum, including the message above, some information about your setup and the stacktrace below:

Stacktrace: 
at InfoCaster.Umbraco.UrlTracker.UI.Installer.UrlTrackerInstallerService.HandleException(Exception ex) in D:\kipusoep\Documents\GitHub\UrlTracker\UI\Installer\UrlTrackerInstallerService.asmx.cs:line 173
at InfoCaster.Umbraco.UrlTracker.UI.Installer.UrlTrackerInstallerService.InstallDashboard() in D:\kipusoep\Documents\GitHub\UrlTracker\UI\Installer\UrlTrackerInstallerService.asmx.cs:line 103
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at System.Web.Script.Services.WebServiceMethodData.CallMethod(Object target, IDictionary`2 parameters)
at System.Web.Script.Services.WebServiceMethodData.CallMethodFromRawParams(Object target, IDictionary`2 parameters)
at System.Web.Script.Services.RestHandler.InvokeMethod(HttpContext context, WebServiceMethodData methodData, IDictionary`2 rawParams)
at System.Web.Script.Services.RestHandler.ExecuteWebServiceCall(HttpContext context, WebServiceMethodData methodData)
at System.Web.Script.Services.RestHandler.ProcessRequest(HttpContext context)
at System.Web.Script.Services.ScriptHandlerFactory.HandlerWrapper.ProcessRequest(HttpContext context)
at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
at System.Web.HttpApplication.PipelineStepManager.ResumeSteps(Exception error)
at System.Web.HttpApplication.BeginProcessRequestNotification(HttpContext context, AsyncCallback cb)
at System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context)
at System.Web.Hosting.PipelineRuntime.ProcessRequestNotificationHelper(IntPtr rootedObjectsPointer, IntPtr nativeRequestContext, IntPtr moduleData, Int32 flags)
at System.Web.Hosting.PipelineRuntime.ProcessRequestNotification(IntPtr rootedObjectsPointer, IntPtr nativeRequestContext, IntPtr moduleData, Int32 flags)
at System.Web.Hosting.UnsafeIISMethods.MgdIndicateCompletion(IntPtr pHandler, RequestNotificationStatus& notificationStatus)
at System.Web.Hosting.PipelineRuntime.ProcessRequestNotificationHelper(IntPtr rootedObjectsPointer, IntPtr nativeRequestContext, IntPtr moduleData, Int32 flags)
at System.Web.Hosting.PipelineRuntime.ProcessRequestNotification(IntPtr rootedObjectsPointer, IntPtr nativeRequestContext, IntPtr moduleData, Int32 flags)
```

**Comment by cgarveyie** [comment]
manually creating the StartupFormsDashboardSection in /Config/Dashboard.config did the trick

```
<section alias="StartupDashboardSection">
    <areas>
        <area>content</area>
    </areas>
    <tab caption="Url Tracker">
        <control addPanel="true">~/Umbraco/UrlTracker/InfoCaster.Umbraco.UrlTracker.UI.UrlTrackerManagerWrapper.ascx</control>
    </tab>
</section>
```
