### ISSUE TITLE
Installed but does not show up

### ISSUE THREAD

**Issue by mortenmoulder** [kipusoep/UrlTracker#158]
I am running Umbraco version 7.5.10 on my Azure server (which I deploy to). My SQL database is also located on Azure and has the same database as my local. 

So:
Local -> Azure DB
Public -> Azure DB
Same database.

When I install the plugin on my local machine, it works just fine. I go to Content -> Url Tracker tab and it just works great. Fantastic package. However, when I then go to `http://my-published-Azure.server/Umbraco` and go to Content, the Url Tracker tab isn't there. Fair enough, as the package was installed locally. So I go and drag'n'drop the package, which gets installed, but the tab still isn't there. I have tried rebooting the server, use incognito mode, use another browser, etc. etc. Nothing has worked.

What can I do here?

**Comment by GambitKZ** [comment]
I believe that somehow "UrlTrackerInstallerService.asmx.cs" have not changed "/config/Dashboard.config". All you need to do is to manually add it on Azure.
![image](https://cloud.githubusercontent.com/assets/17333840/25494918/2310c28a-2b9d-11e7-9072-4d6b2f392455.png)

**Comment by mortenmoulder** [comment]
@GambitKZ Thanks. I updated to 7.6 and now it appears. However, for some odd reason, the file was not found after I publish it:

> Could not load control: '/Umbraco/UrlTracker/InfoCaster.Umbraco.UrlTracker.UI.UrlTrackerManagerWrapper.ascx'. 
Error message: System.Web.HttpException (0x80004005): The file '/Umbraco/UrlTracker/InfoCaster.Umbraco.UrlTracker.UI.UrlTrackerManagerWrapper.ascx' does not exist. at System.Web.UI.Util.CheckVirtualFileExists(VirtualPath virtualPath) at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) at System.Web.UI.TemplateControl.LoadControl(VirtualPath virtualPath) at Umbraco.Web.UI.Umbraco.Dashboard.UserControlProxy.OnInit(EventArgs e)

I cannot find the folder UrlTracker in my local directory either (under /Umbraco/), but it does work fine on local.

**Comment by jsmilovic** [comment]
I have the same error as @mortenmoulder 
I'm running Umbraco 7.4.1 
It works fine locally but when I deploy to my server I get this same error.

I performed an uninstall, then reinstalled it and kept an eye on the log files here is what I got

```

2017-05-31 21:16:10,529 [P5084/D18/T9] INFO  Umbraco.Core.PluginManager - Completed resolution of types of umbraco.interfaces.ITree, found 0 (took 1ms)
 2017-05-31 21:16:11,123 [P5084/D18/T35] ERROR Umbraco.Core.UmbracoApplicationBase - An unhandled exception occurred
System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> System.Web.HttpException (0x80004005): The file '/Umbraco/UrlTracker/InfoCaster.Umbraco.UrlTracker.UI.Installer.UrlTrackerInstaller.ascx' does not exist.
   at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResult(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean ensureIsUpToDate)
   at System.Web.UI.TemplateControl.LoadControl(VirtualPath virtualPath)
   at umbraco.presentation.developer.packages.Installer.ProcessInstall(String currentStep)
   at umbraco.presentation.developer.packages.Installer.Page_Load(Object sender, EventArgs e)
   at umbraco.BasePages.BasePage.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

```

**Comment by blachawk** [comment]
As far as Umbraco 7.6.3. UrlRewriting.config from the config file has been removed.  Does this impact the use of UrlTracker for this version of Umbraco?

**Comment by daniel-chenery** [comment]
Are you still seeing this problem?
I'm unable to replicate it

**Comment by avatart0ph** [comment]
i am getting this issue as well.

adding this to Dashboard.config works
```
<section alias="RedirectUrlManagement">
    <areas>
      <area>content</area>
    </areas>
    <tab caption="Url Tracker">
      <control addPanel="true">
        /Umbraco/UrlTracker/InfoCaster.Umbraco.UrlTracker.UI.UrlTrackerManagerWrapper.ascx
      </control>
    </tab>
  </section>
```

**Comment by daniel-chenery** [comment]
What are the permissions for IIS_USR on this file?

**Comment by kipusoep** [comment]
Had the same problem just now (no dashboard installed). No permissions issue that's for sure.

**Comment by Auraya86** [comment]
@kipusoep  I am using Umbraco 7.3.0, so maybe the problem is here. The documentation describes that I shall not use this umbraco version with the url tracker. So I don't think it suffices to add an entry in die dashboard.config, because there is no directory for the urltracker in the umbraco-Folder. Thanks for your help.

**Comment by kipusoep** [comment]
I don't know why you think there should be a urltracker directory in the umbraco folder? There shouldn't be one...

**Comment by Auraya86** [comment]
because it is listed here. I will give it a try, so maybe I am overthinking here :)


<section alias="RedirectUrlManagement">
    <areas>
      <area>content</area>
    </areas>
    <tab caption="Url Tracker">
      <control addPanel="true">
        /Umbraco/UrlTracker/InfoCaster.Umbraco.UrlTracker.UI.UrlTrackerManagerWrapper.ascx
      </control>
    </tab>
  </section>

**Comment by kipusoep** [comment]
That's a [virtual path for embedded resources](https://github.com/kipusoep/UrlTracker/blob/master/Providers/EmbeddedResourcesVirtualPathProvider.cs) in the assembly :-)
