### ISSUE TITLE
UrlTracker disappears in CMS

### ISSUE THREAD

**Issue by Auraya86** [kipusoep/UrlTracker#193]
Hi,
we have a strang behaviour with the UrlTracker Package. Installation is succesful and the user can adjust the tracking-variables, but after awhile the UrlTracker is away in the CMS?

The Url-Tracker seems to use an absolute path. Don't know where it is coming from? `D:\kipusoep\Documents\GitHub\UrlTracker\UrlTrackerApplicationEventHandler.cs`

    2018-11-05 10:26:46,414 [P5788/D27/T58] ERROR InfoCaster.Umbraco.UrlTracker.Helpers.LoggingHelper - Error reading JObject from JsonReader. Path '', line 0, position 0.
    Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
       at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader)
       at Newtonsoft.Json.Linq.JObject.Parse(String json)
       at InfoCaster.Umbraco.UrlTracker.UrlTrackerApplicationEventHandler.ContentService_Publishing(IPublishingStrategy sender, PublishEventArgs`1 e) in D:\kipusoep\Documents\GitHub\UrlTracker\UrlTrackerApplicationEventHandler.cs:line 116
     2018-11-05 10:26:46,414 [P5788/D27/T58] ERROR InfoCaster.Umbraco.UrlTracker.Helpers.LoggingHelper - Error reading JObject from JsonReader. Path '', line 0, position 0.
    Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
       at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader)
       at Newtonsoft.Json.Linq.JObject.Parse(String json)
       at InfoCaster.Umbraco.UrlTracker.UrlTrackerApplicationEventHandler.ContentService_Publishing(IPublishingStrategy sender, PublishEventArgs`1 e) in D:\kipusoep\Documents\GitHub\UrlTracker\UrlTrackerApplicationEventHandler.cs:line 11

**Comment by Auraya86** [comment]
Hi, does anyone have a fix for this or do you need more information from me?

**Comment by kipusoep** [comment]
I can't tell you why the UrlTracker dashboard is getting removed from the dashboard.config. I've never seen that before, so it must be something specific to your website.  
The error you posted is related to some code specific to the _Epiphany.SeoMetadata_ plug-in, so something's going wrong there.  
Do you have the most recent version of the UrlTracker installed? Might help if you update it if not.  

The path you posted is the path where the UrlTracker resides on my computer. Nothing special about that and no need to worry :-)

**Comment by Auraya86** [comment]
Thank you very much for your reply :)  Can you shortly describe me where you see the hint that this epiphany.seoMetadata-Plugin could be the reason for the error message?

I thought the error is that the Plugin tries to read a JSON-Object in UrlTrackerApplicationEventHandler.cs, but this file doesn't exist on my system. So I thought there is a path problem in this file, because it has to be relative and not absolute.

**Comment by Auraya86** [comment]
aah ok, good hint, thank you :)

**Comment by Auraya86** [comment]
@kipusoep  maybe you can show me an example of what is need in the dashboard.config for the UrlTracker? Maybe this temporarily solves my problem with the url tracker?

**Comment by kipusoep** [comment]
https://github.com/kipusoep/UrlTracker/issues/158#issuecomment-330419752

**Comment by Auraya86** [comment]
Issue solved with

adding this to Dashboard.config works

```
<section alias="RedirectUrlManagement">
    <areas>
      <area>content</area>
    </areas>
    <tab caption="Url Tracker">
      <control addPanel="true">
        /Umbraco/UrlTracker/InfoCaster.Umbraco.UrlTracker.UI.UrlTrackerManagerWrapper.ascx
      </control>
    </tab>
  </section>

```
