### ISSUE TITLE
Exception when upgrading

### ISSUE THREAD

**Issue by Myster** [kipusoep/UrlTracker#66]
Upgrading from 2.0 (based on what the DLL version says) to v3.5
I got this not too helpful error, looking at the src, the only lines mentioned are the exception handling lines.

```
Previous version found! Would you like to migrate the existing data?

Yes please
Migrating existing data.

Migrating data failed: Object reference not set to an instance of an object. | Stacktrace: at InfoCaster.Umbraco.UrlTracker.UI.Installer.UrlTrackerInstallerService.HandleException(Exception ex) in d:\kipusoep\Documents\GitHub\UrlTracker\UI\Installer\UrlTrackerInstallerService.asmx.cs:line 172
 at InfoCaster.Umbraco.UrlTracker.UI.Installer.UrlTrackerInstallerService.MigrateData() in d:\kipusoep\Documents\GitHub\UrlTracker\UI\Installer\UrlTrackerInstallerService.asmx.cs:line 159
 at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
 at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
 at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
 at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
 at System.Web.Script.Services.WebServiceMethodData.CallMethod(Object target, IDictionary`2 parameters)
 at System.Web.Script.Services.WebServiceMethodData.CallMethodFromRawParams(Object target, IDictionary`2 parameters)
 at System.Web.Script.Services.RestHandler.InvokeMethod(HttpContext context, WebServiceMethodData methodData, IDictionary`2 rawParams)
 at System.Web.Script.Services.RestHandler.ExecuteWebServiceCall(HttpContext context, WebServiceMethodData methodData)
 at System.Web.Script.Services.RestHandler.ProcessRequest(HttpContext context)
 at System.Web.Script.Services.ScriptHandlerFactory.HandlerWrapper.ProcessRequest(HttpContext context)
 at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
 at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
 at System.Web.HttpApplication.PipelineStepManager.ResumeSteps(Exception error)
 at System.Web.HttpApplication.BeginProcessRequestNotification(HttpContext context, AsyncCallback cb)
 at System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context)
 at System.Web.Hosting.PipelineRuntime.ProcessRequestNotificationHelper(IntPtr rootedObjectsPointer, IntPtr nativeRequestContext, IntPtr moduleData, Int32 flags)
 at System.Web.Hosting.PipelineRuntime.ProcessRequestNotification(IntPtr rootedObjectsPointer, IntPtr nativeRequestContext, IntPtr moduleData, Int32 flags)
 at System.Web.Hosting.UnsafeIISMethods.MgdIndicateCompletion(IntPtr pHandler, RequestNotificationStatus& notificationStatus)
 at System.Web.Hosting.PipelineRuntime.ProcessRequestNotificationHelper(IntPtr rootedObjectsPointer, IntPtr nativeRequestContext, IntPtr moduleData, Int32 flags)
 at System.Web.Hosting.PipelineRuntime.ProcessRequestNotification(IntPtr rootedObjectsPointer, IntPtr nativeRequestContext, IntPtr moduleData, Int32 flags)

All done :-)
The Url Tracker interface can be found as a dashboard in the Content section.
Go to Content and look on the right for a tab called Url Tracker.

Happy Url Tracking!
```

**Comment by kipusoep** [comment]
The migration script is only necessary when upgrading from v1. The installer detects this by searching for a SQL table called 'infocaster301'.
Have you already ran the migration before? Like when you had v1 installed and upgraded to v2?

**Comment by Myster** [comment]
Ok, looks like the old version of the website had a src build of infocaster for some reason, so the DLL version is probably wrong. The new site is actually a fresh install of umbraco7 with a fresh install of the latest infocaster (we're just keeping the old DB) in the old db there is an infocaster301 table but NO icUrlTracker table.

Also, I've found if I run `UrlTrackerRepository.MigrateData()` myself it works and populates the icUrlTracker table.
