### ISSUE TITLE
Exception on certain paths

### ISSUE THREAD

**Issue by ZNS** [kipusoep/UrlTracker#84]
When I click certain rows in either the "404 not found view" or the "Url tracker view" I get a 500 exception. This is what its says in the log:

```
2015-06-30 00:37:56,447 [6] ERROR Umbraco.Core.UmbracoApplicationBase - [T31/D2] An unhandled exception occurred
System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at InfoCaster.Umbraco.UrlTracker.Repositories.UrlTrackerRepository.GetNotFoundEntryByRootAndUrl(Int32 redirectRootNodeId, String url)
   at InfoCaster.Umbraco.UrlTracker.UI.UrlTrackerManager.LoadDetail(Object dataKey, String secondKey)
   at System.Web.UI.WebControls.GridView.HandleEvent(EventArgs e, Boolean causesValidation, String validationGroup)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at ASP.umbraco_urltracker_infocaster_umbraco_urltracker_ui_urltrackermanager_aspx.ProcessRequest(HttpContext context) in c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\0595f39f\1f60f78c\App_Web_infocaster.umbraco.urltracker.ui.urltrackermanager.aspx.6b1c27ca.qahf956x.0.cs:line 0
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

**Comment by ZNS** [comment]
This is in version 3.8

**Comment by ZNS** [comment]
Some more info on this from the event logs:
```
Exception information: 
    Exception type: ArgumentOutOfRangeException 
    Exception message: 'ddlRootNode' has a SelectedValue which is invalid because it does not exist in the list of items.
Parameter name: value
   at System.Web.UI.WebControls.ListControl.set_SelectedValue(String value)
   at InfoCaster.Umbraco.UrlTracker.UI.UserControls.CustomView.LoadView()
   at InfoCaster.Umbraco.UrlTracker.UI.UrlTrackerManager.lbSwitchToNormalView_Click(Object sender, EventArgs e)
   at System.Web.UI.WebControls.GridView.HandleEvent(EventArgs e, Boolean causesValidation, String validationGroup)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

Request information: 
    Request URL: /umbraco/UrlTracker/InfoCaster.Umbraco.UrlTracker.UI.UrlTrackerManager.aspx?culture=en-GB&uiculture=en-GB 
    Request path: /umbraco/UrlTracker/InfoCaster.Umbraco.UrlTracker.UI.UrlTrackerManager.aspx 
 
Thread information: 
    Stack trace:    at System.Web.UI.WebControls.ListControl.set_SelectedValue(String value)
   at InfoCaster.Umbraco.UrlTracker.UI.UserControls.CustomView.LoadView()
   at InfoCaster.Umbraco.UrlTracker.UI.UrlTrackerManager.lbSwitchToNormalView_Click(Object sender, EventArgs e)
   at System.Web.UI.WebControls.GridView.HandleEvent(EventArgs e, Boolean causesValidation, String validationGroup)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
```
