### ISSUE TITLE
Collection was modified error

### ISSUE THREAD

**Issue by xumix** [kipusoep/UrlTracker#96]
Don't know the exact conditions but:
```
2015-10-02 10:20:44,436 [32] ERROR Umbraco.Core.UmbracoApplicationBase - [Thread 39] An unhandled exception occurred
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at InfoCaster.Umbraco.UrlTracker.Modules.UrlTrackerModule.UrlTrackerDo(String callingEventName, Boolean ignoreHttpStatusCode)
   at InfoCaster.Umbraco.UrlTracker.Modules.UrlTrackerModule.context_AcquireRequestState(Object sender, EventArgs e)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

**Comment by kipusoep** [comment]
And you don't even know the Umbraco version? And the Url Tracker version? I need more information instead of just pasting exceptions here.

**Comment by xumix** [comment]
Umbraco 6.2.3, tracker: 3.8
Btw, the exception is pretty obvious, and should be easy to find (some foreach without .ToArray() for example)

**Comment by kipusoep** [comment]
Ah, then it won't be a problem for you to fix this and create a PR, is it?

**Comment by xumix** [comment]
@kipusoep looks like f.. you, ok then

**Comment by kipusoep** [comment]
No that's not it, it's just the way you, and others in the past, created this issue; just pasting the exception without taking any time to create a proper bug report.
I hope you'll understand that this can be frustrating.

**Comment by xumix** [comment]
```
foreach (var match in forcedRedirects.Select(x => new { UrlTrackerModel = x, Regex = new Regex(x.OldRegex) }).Where(x => x.Regex.IsMatch(url)))
```
Looks like this

**Comment by granthughes** [comment]
PR #100 was merged in. Closing issue
